### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by probonopd** [stapelberg/airscan#2]
```
me@host:~$ '/home/me/Downloads/go/bin/go' get  github.com/stapelberg/airscan/cmd/airscan1

me@host:~$ '/home/me/Downloads/go/bin/go' install github.com/stapelberg/airscan/cmd/airscan1

me@host:~$ ./go/bin/airscan1
2020/08/16 14:35:07 finding device for 5s (use -timeout=0 for unlimited)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7111fa]

goroutine 1 [running]:
github.com/stapelberg/airscan.NewClientForService(0x0, 0x0)
	/home/me/go/src/github.com/stapelberg/airscan/airscan.go:333 +0x3a
main.(*airscanner).scan1(0xc0000de580, 0x0, 0x0)
	/home/me/go/src/github.com/stapelberg/airscan/cmd/airscan1/airscan1.go:173 +0x52
main.airscan1(0x0, 0x0)
	/home/me/go/src/github.com/stapelberg/airscan/cmd/airscan1/airscan1.go:155 +0x6e9
main.main()
	/home/me/go/src/github.com/stapelberg/airscan/cmd/airscan1/airscan1.go:238 +0x25
```

This is my printer (I do not know whether it _should_ be supported): HP LaserJet 200 colorMFP M276n. It is being advertised with Zeroconf as ` _scanner._tcp`.

**Comment by probonopd** [comment]
Is there an easy way to find out, from looking at the output of `avahi-browse -ar`, whether a scanner _should_ be supported?

**Comment by probonopd** [comment]
Found it:

https://github.com/stapelberg/airscan/blob/15a04490cd177b5b9b76c884b04b0b56b9201bee/airscan.go#L36

Unfortunately my printer does not publish that service.
